name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11', pypy-3.7]
        exclude:
          # https://www.lfd.uci.edu/~gohlke/pythonlibs/ has no permalinks (for libxml2).
          - os: windows-latest
            python-version: '3.11'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == 'pypy-3.7'
        run: |
          sudo apt update
          sudo apt install libxml2-dev libxslt-dev
      - run: pip install .[test]
      - name: Test entry point
        run: |
          curl https://raw.githubusercontent.com/open-contracting/infrastructure/0.9-dev/docs/examples/example.json > example.json
          libcoveoc4ids example.json
      # "orjson does not support PyPy" and fails to install. https://pypi.org/project/orjson/
      - if: matrix.python-version != 'pypy-3.7'
        name: Test
        run: |
          coverage run --append --source=libcoveoc4ids -m pytest -W error
          pip install orjson
          coverage run --append --source=libcoveoc4ids -m pytest -W error
          pip uninstall -y orjson
      - if: matrix.python-version == 'pypy-3.7'
        name: Test
        run: pytest -W error --cov libcoveoc4ids
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
