name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # lib-cove is a blocker for pypy-3.9.
        # https://github.com/OpenDataServices/lib-cove/pull/121
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12']
        exclude:
          # https://www.lfd.uci.edu/~gohlke/pythonlibs/ has no permalinks (for libxml2).
          - os: windows-latest
            python-version: '3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg
      - if: matrix.os == 'ubuntu-latest' && matrix.python-version == 'pypy-3.9'
        run: |
          sudo apt update
          sudo apt install libxml2-dev libxslt-dev libgeos-dev
      - run: pip install .[test]
      - if: matrix.python-version == 'pypy-3.9'
        # https://github.com/django/asgiref/issues/393
        run: pip install 'asgiref<3.7'
      - name: Test entry point
        run: |
          curl https://raw.githubusercontent.com/open-contracting/infrastructure/0.9-dev/docs/examples/example.json > example.json
          libcoveoc4ids example.json
      # https://github.com/OpenDataServices/lib-cove/issues/112
      - run: pytest -W error -W ignore::DeprecationWarning:libcove.lib.common --cov libcoveoc4ids
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
